### ISSUE TITLE
Missing Translation for iso3166. Extension not starting. 

### ISSUE THREAD

**Issue by duracell80** [RalfLangeDresden/mopidy-radiobrowser#1]
Hey I found an error when trying to run this with:
sudo python3 setup.py install

Here is the log output with this being the most informative:
`FileNotFoundError: [Errno 2] No translation file found for domain: 'iso3166'"`

I believe it is this line in translator.py
`localLanguage = gettext.translation('iso3166', pycountry.LOCALES_DIR, languages=[actualLocale[0]])`

INFO     2020-06-05 21:22:36,003 [1256:MainThread] mopidy.__main__
  Enabled extensions: m3u, stream, radiobrowser, file, podcast-itunes, podcast, http, somafm, musicbox_webclient, youtube, tunein, softwaremixer
INFO     2020-06-05 21:22:36,003 [1256:MainThread] mopidy.__main__
  Disabled extensions: none
ERROR    2020-06-05 21:22:37,523 [1256:MainThread] mopidy.__main__
  Extension radiobrowser failed during setup. This might have left the registry in a bad state.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/__main__.py", line 129, in main
    extension.setup(registry)
  File "/usr/local/lib/python3.7/dist-packages/Mopidy_RadioBrowser-3.0.1-py3.7.egg/mopidy_radiobrowser/__init__.py", line 41, in setup
    from .backend import RadioBrowserBackend
  File "/usr/local/lib/python3.7/dist-packages/Mopidy_RadioBrowser-3.0.1-py3.7.egg/mopidy_radiobrowser/backend.py", line 10, in <module>
    from .library import RadioBrowserLibrary
  File "/usr/local/lib/python3.7/dist-packages/Mopidy_RadioBrowser-3.0.1-py3.7.egg/mopidy_radiobrowser/library.py", line 6, in <module>
    from mopidy_radiobrowser import translator
  File "/usr/local/lib/python3.7/dist-packages/Mopidy_RadioBrowser-3.0.1-py3.7.egg/mopidy_radiobrowser/translator.py", line 13, in <module>
    localLanguage = gettext.translation('iso3166', pycountry.LOCALES_DIR, languages=[actualLocale[0]])
  File "/usr/lib/python3.7/gettext.py", line 539, in translation
    'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'iso3166'

Great extension I would like to help maintain.

**Comment by duracell80** [comment]
Aha! I think I have the answer change "iso3166" to "iso3166-2"
